name: 'beanstalk-ens-action'
description:
  'Create a envvars.config file for AWS Elastic Beanstalk deployments'
author: 'luke@basal.dev'

branding:
  icon: 'file-plus'
  color: 'gray-dark'

inputs:
  filename:
    description: 'The filename for the envfile'
    default: 'envvars.config'
  directory:
    description: 'The directory to put the envfile in'
    default: '.ebextensions'
  fail_on_empty:
    description: 'Fail if an env value is empty'
    default: 'false'
  sort_keys:
    description: 'Sort the keys alphabetically'
    default: 'false'
  json:
    description: 'JSON representation of your environment variable key/values'

outputs:
  result:
    description: 'envvars.config file'

runs:
  using: 'node16'
  main: 'dist/index.js'
